// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace BugzillaDotNet.Entity.Bugs
{

    public class Bug
    {

        [JsonProperty("alias")]
        public string[] Alias { get; set; }

        [JsonProperty("assigned_to")]
        public string AssignedTo { get; set; }

        [JsonProperty("assigned_to_detail")]
        public AssignedToDetail AssignedToDetail { get; set; }

        [JsonProperty("blocks")]
        public int[] Blocks { get; set; }

        [JsonProperty("cc")]
        public string[] Cc { get; set; }

        [JsonProperty("cc_detail")]
        public CcDetail[] CcDetail { get; set; }

        [JsonProperty("cf_bug_id")]
        public object CfBugId { get; set; }

        [JsonProperty("cf_date")]
        public string CfDate { get; set; }

        [JsonProperty("cf_drop_down")]
        public string CfDropDown { get; set; }

        [JsonProperty("cf_free_text")]
        public string CfFreeText { get; set; }

        [JsonProperty("cf_large_text")]
        public string CfLargeText { get; set; }

        [JsonProperty("cf_mulitple_select")]
        public object[] CfMulitpleSelect { get; set; }

        [JsonProperty("classification")]
        public string Classification { get; set; }

        [JsonProperty("component")]
        public string Component { get; set; }

        [JsonProperty("creation_time")]
        public string CreationTime { get; set; }

        [JsonProperty("creator")]
        public string Creator { get; set; }

        [JsonProperty("creator_detail")]
        public CreatorDetail CreatorDetail { get; set; }

        [JsonProperty("deadline")]
        public string Deadline { get; set; }

        [JsonProperty("depends_on")]
        public int[] DependsOn { get; set; }

        [JsonProperty("dupe_of")]
        public object DupeOf { get; set; }

        [JsonProperty("flags")]
        public Flag[] Flags { get; set; }

        [JsonProperty("groups")]
        public object[] Groups { get; set; }

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("is_cc_accessible")]
        public bool IsCcAccessible { get; set; }

        [JsonProperty("is_confirmed")]
        public bool IsConfirmed { get; set; }

        [JsonProperty("is_creator_accessible")]
        public bool IsCreatorAccessible { get; set; }

        [JsonProperty("is_open")]
        public bool IsOpen { get; set; }

        [JsonProperty("keywords")]
        public string[] Keywords { get; set; }

        [JsonProperty("last_change_time")]
        public string LastChangeTime { get; set; }

        [JsonProperty("op_sys")]
        public string OpSys { get; set; }

        [JsonProperty("platform")]
        public string Platform { get; set; }

        [JsonProperty("priority")]
        public string Priority { get; set; }

        [JsonProperty("product")]
        public string Product { get; set; }

        [JsonProperty("qa_contact")]
        public string QaContact { get; set; }

        [JsonProperty("resolution")]
        public string Resolution { get; set; }

        [JsonProperty("see_also")]
        public string[] SeeAlso { get; set; }

        [JsonProperty("severity")]
        public string Severity { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("summary")]
        public string Summary { get; set; }

        [JsonProperty("target_milestone")]
        public string TargetMilestone { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("version")]
        public string Version { get; set; }

        [JsonProperty("whiteboard")]
        public string Whiteboard { get; set; }
    }

}
