// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace BugzillaDotNet.Entity.Bugs
{

    public class Flag
    {

        [JsonProperty("creation_date")]
        public string CreationDate { get; set; }

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("modification_date")]
        public string ModificationDate { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("setter")]
        public string Setter { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("type_id")]
        public int TypeId { get; set; }

        [JsonProperty("requestee")]
        public string Requestee { get; set; }
    }

}
