// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace BugzillaDotNet.Entity.BugHistory
{

    public class Bug
    {

        [JsonProperty("alias")]
        public object[] Alias { get; set; }

        [JsonProperty("history")]
        public History[] History { get; set; }

        [JsonProperty("id")]
        public int Id { get; set; }
    }

}
