// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace BugzillaDotNet.Entity.BugHistory
{

    public class History
    {

        [JsonProperty("when")]
        public string When { get; set; }

        [JsonProperty("who")]
        public string Who { get; set; }

        [JsonProperty("changes")]
        public Change[] Changes { get; set; }
    }

}
